### ISSUE TITLE
HBPR-4 GUI Updates

### ISSUE THREAD

**Issue by Devon-H** [UVicRocketry/Hybrid_Controls_System#9]
The following is a brief list taken from a discussion with Kris and JJ on Feb. 12, 2022.
- fix toggle switches (ask Kris Lemieux)
- Remove feed system schematic
- relocate buttons
- move mission critical buttons (Fire, abort, vent) to physical buttons
- make custom test file type for config

**Comment by klemie** [comment]
Might be good to break this up into multiple issues. Thanks for following my naming standard now
